spring.main.allow-bean-definition-overriding: true
app.gateway: http://gdev.test

#u
#app.gateway: http://127.0.0.1:8080
server:
  port: 9000
  servlet.session.cookie.name: Your_custome_name
  servlet:
    context-path : /account

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace

spring:
  security:
#    user:
#      name: user1
#      password: password
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "${app.gateway}/login/oauth2/code/messaging-client-oidc"
                - "${app.gateway}/authorized"
              post-logout-redirect-uris:
                - "${app.gateway}/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3307/testsecurity
    username: test1
    password: test1
    driver-class-name: org.mariadb.jdbc.Driver
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect

  
