server:
  port: 8090
#  ssl:
#    bundle: messages-resource
#    client-auth: need

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

