app:
  base-uri: http://gdev.test
  gateway: http://gdev.test
  account: http://account.gdev.test
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "${app.gateway}/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: messaging-client-oidc
        provider:
          spring:
            issuer-uri: ${app.account}
  cloud:
    gateway:
      mvc:
        routes:
          - id: userinfo
            uri: http://localhost:9000
            predicates:
              - Path=/userinfo
            filters:
              - TokenRelay=
          - id: messages
            uri: http://localhost:8090
            predicates:
              - Path=/messages
            filters:
              - TokenRelay=

